
import React, { useState, useEffect } from 'react';
import ShoeCard from './ShoeCard';

const Dashboard = () => {
    const [data, setData] = useState(null);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState(null);

    useEffect(() => {
        // Fetch the JSON file generated by the scraper
        // In development, this file might not exist yet if not copied, but we assume it's there for now.
        // In production (GitHub Pages), it will be served from root.
        // In production (GitHub Pages), it will be served from root.
        fetch('data.json')
            .then(response => {
                if (!response.ok) {
                    throw new Error('Data file not found (run scraper first!)');
                }
                return response.json();
            })
            .then(jsonData => {
                setData(jsonData);
                setLoading(false);
            })
            .catch(err => {
                console.error("Error fetching data:", err);
                setError(err.message);
                setLoading(false);
            });
    }, []);

    const [searchQuery, setSearchQuery] = useState('');

    if (loading) return <div className="loading-screen">Loading Monitor...</div>;
    if (error) return <div className="error-screen">Error: {error}</div>;
    if (!data) return <div className="error-screen">No Data Available</div>;

    const { results, updatedAt, searchTerm } = data;

    // Filter results based on client-side search
    const filteredResults = results.filter(item =>
        item.title.toLowerCase().includes(searchQuery.toLowerCase()) ||
        item.store.toLowerCase().includes(searchQuery.toLowerCase())
    );

    // Calculate Stats
    const totalFound = filteredResults.length;
    const lowestPrice = filteredResults.reduce((min, item) => (item.price < min ? item.price : min), Infinity);
    const bestPriceDisplay = totalFound > 0 ? `₪${lowestPrice}` : '-';

    // Format Date
    const lastUpdated = new Date(updatedAt).toLocaleString();

    return (
        <div className="dashboard-container">
            <header className="dashboard-header">
                <h1>Sneaker Monitor 👟</h1>
                <p className="last-updated">Last Updated: {lastUpdated}</p>

                <div className="search-bar-container">
                    <input
                        type="text"
                        placeholder="Search model, store..."
                        value={searchQuery}
                        onChange={(e) => setSearchQuery(e.target.value)}
                        className="search-input"
                    />
                </div>

                <div className="stats-grid">
                    <div className="stat-card">
                        <h3>Found</h3>
                        <p className="stat-value">{totalFound}</p>
                    </div>
                    <div className="stat-card">
                        <h3>Best Price</h3>
                        <p className="stat-value">{bestPriceDisplay}</p>
                    </div>
                    <div className="stat-card">
                        <h3>Scraper Query</h3>
                        <p className="stat-value small">{searchTerm}</p>
                    </div>
                </div>
            </header>

            <main className="results-grid">
                {filteredResults.length === 0 ? (
                    <div className="empty-state">
                        No matches found for "{searchQuery}"
                        <br />
                        (Scraped for: {searchTerm})
                    </div>
                ) : (
                    filteredResults.map((item, index) => (
                        <ShoeCard key={index} item={item} />
                    ))
                )}
            </main>
        </div>
    );
};

export default Dashboard;
